### ISSUE TITLE
LargeLoadingDialog显示无法修改messge信息，调试信息如下截图

### ISSUE THREAD

**Issue by goo2018** [the-pig-of-jungle/smart-show#12]
![image](https://user-images.githubusercontent.com/15153772/53310980-4b662980-38ea-11e9-92a0-ea561edc9b31.png)

![image](https://user-images.githubusercontent.com/15153772/53310952-df83c100-38e9-11e9-83e0-8ac756673928.png)
调试时看到获取的msgView为null导致设置的显示信息无效

**Comment by the-pig-of-jungle** [comment]
稍等，我看一下。稍后回复

**Comment by the-pig-of-jungle** [comment]
抱歉，这是一个bug，middle loading 和Large loading的布局文件里textview的id没有设置成统一的smart_show_loading_message_view，马上修复，发布新版本。

**Comment by the-pig-of-jungle** [comment]
问题已修复，请使用最新版本2.6.1
