### ISSUE TITLE
建议添加一个Dialog取消的回调方法

### ISSUE THREAD

**Issue by goo2018** [the-pig-of-jungle/smart-show#13]
建议添加一个Dialog取消的回调方法，当dialog被用户主动back时的回调，类似系统dialog的OnCancelListener回调，这样我们可以方便我们处理一些取消事件，因为不是所有的弹框都会有界面显示的取消按钮

**Comment by the-pig-of-jungle** [comment]
好的。下个版本发布。可以扫那个微信二维码交流群，提建议。都会得到改善。谢谢你的支持
