### ISSUE TITLE
最新的2.7.0版本分别引入dialog、toast找不到smartshow

### ISSUE THREAD

**Issue by wlsh** [the-pig-of-jungle/smart-show#19]
`implementation 'com.github.the-pig-of-jungle.smart-show:toast:2.7.0'
    implementation 'com.github.the-pig-of-jungle.smart-show:dialog:2.7.0'`

**Comment by wlsh** [comment]
必须要依赖core然后在引入dialog和toast么？

**Comment by the-pig-of-jungle** [comment]
显示依赖core库，implementation 'com.github.the-pig-of-jungle.smart-show:toast:2.7.0'

**Comment by wlsh** [comment]
> 显示依赖core库，implementation 'com.github.the-pig-of-jungle.smart-show:toast:2.7.0'

ok，依赖core然后引入toast解决了
