### ISSUE TITLE
能出个分支支持AndroidX么？

### ISSUE THREAD

**Issue by wlsh** [the-pig-of-jungle/smart-show#27]

**Comment by the-pig-of-jungle** [comment]
你好，将尽快推出，感谢支持

**Comment by the-pig-of-jungle** [comment]
你好，现在已经支持androidx版了。版本好前加一个“x”前缀就是androidx版。如：
implementation 'com.github.the-pig-of-jungle.smart-show:toast:x2.8.2'

**Comment by wlsh** [comment]
> 你好，现在已经支持androidx版了。版本好前加一个“x”前缀就是androidx版。如：
> implementation 'com.github.the-pig-of-jungle.smart-show:toast:x2.8.2'
谢谢
