### ISSUE TITLE
魅族Flyme 7.3.10A 锁屏状态无法显示NotificationDialog()

### ISSUE THREAD

**Issue by Black-Knights** [the-pig-of-jungle/smart-show#29]
魅族Flyme 7.3.10A 锁屏状态无法显示NotificationDialog()，有没有什么解决方案？

**Comment by the-pig-of-jungle** [comment]
Dialog是依附于activity的，锁屏状态下显示的窗口属于独立悬浮窗，需要较高的权限。

**Comment by Black-Knights** [comment]
设置里所有权限都给了，还是没显示出来，是不是没救了？

**Comment by the-pig-of-jungle** [comment]
不是，不是你没给我权限，是dialog根本不能在锁屏界面显示。只有独立悬浮窗才可以。目前库内并没有悬浮窗。你解锁后应该就看到dialog了吧？

**Comment by Black-Knights** [comment]
解锁后屏幕变灰，没有看到dialog（应该是界面不见了），点击返回键后屏幕恢复正常（dialog取消了）。在华为P20上锁屏后能正常弹dialog。

**Comment by Black-Knights** [comment]
还有补充一下，我所谓的弹dialog是指在Activity上显示dialog，解锁屏幕后，可以在Activity上正常显示dialog

**Comment by the-pig-of-jungle** [comment]
哦哦，我明白了，我在flyme7.2上没有复现，然后你那边对话框消失后是否有错误日志？

**Comment by the-pig-of-jungle** [comment]
手里没有flyme7.3的手机。待会我看看魅族开发者官网是否提供远程调试

**Comment by Black-Knights** [comment]
具体现象已给coder_zzq@163.com邮箱发送邮件，基本定为系统问题了。

**Comment by Black-Knights** [comment]
close
