### ISSUE TITLE
判断 activity的状态是可以操作UI 

### ISSUE THREAD

**Issue by niemj** [the-pig-of-jungle/smart-show#8]
** 
123      * 判断 activity的状态是可以操作UI 
124      * @param activity 
125      * @return 
126      */ 
127     public static boolean isUpdateActivityUIPermitted(Activity activity) { 
128         return activity != null || !activity.isFinishing() || !Utils.isActivityDestroyed(activity); 
129     } 
130 } 
你这个判断有问题吧？activity为null试试。

**Comment by the-pig-of-jungle** [comment]
抱歉，这个代码搞错了，应该是&&的关系，不小心写成 || 了，等我修复下

**Comment by the-pig-of-jungle** [comment]
问题已修复，最新版本2.5.4
