### ISSUE TITLE
在SmartTopbar文字前面是否可以加一个imageView呢？

### ISSUE THREAD

**Issue by Dhy521** [the-pig-of-jungle/smart-show#9]
在SmartTopbar文字前面是否可以加一个imageView呢  
![image](https://user-images.githubusercontent.com/23187670/53138599-e2b53f00-35c1-11e9-8297-32181ce5781f.png)
类似这个样子的 博主

**Comment by Dhy521** [comment]
![image](https://user-images.githubusercontent.com/23187670/53138672-0c6e6600-35c2-11e9-8d56-a8c255ce29ed.png)

**Comment by the-pig-of-jungle** [comment]
可以的，目前没有向外暴露接口。下一版本，可以考虑加入

**Comment by Dhy521** [comment]
1.请问博主下一次版本什么时候提交呢  是否可以最近可以提交一下
2.请问设置普通Toats的时候 没有找到可以定制的代码 这个需要自己 比如设置背景颜色 弧度大小 因为我看TypeToats是支持定制 也可以设置view

**Comment by Dhy521** [comment]
![image](https://user-images.githubusercontent.com/23187670/53140336-560d7f80-35c7-11e9-8fd7-879fbd0f65a7.png)
有一个小小的建议就是这个是否可以向外暴露个接口 就是支持 显示 开关或者替换 这个默认图片的 这样扩展性更强一些

**Comment by the-pig-of-jungle** [comment]
1.我尽量最近提交一个。下周一前提交。
2。普通Toast也可以。如果你不适用自定义布局，仅仅是在原有布局上改改背景色文字等，可以调用
 SmartToast.setting()，然后又一系列设置的方法。如果使用自己的布局，调用 SmartToast.setting()后，有个view方法传递自定义布局，并且在processView方法里配置这个布局。

**Comment by the-pig-of-jungle** [comment]
type类型的消息暂时不支持自定义布局。view方法是对普通toast起作用的。目前typetoast只支持换主题色。后续版本放开。

**Comment by the-pig-of-jungle** [comment]
另外setting配置是全局起效果的。最好在application里调用。

**Comment by Dhy521** [comment]
好的 
感谢博主
框架很不错 以后会继续沿用

**Comment by the-pig-of-jungle** [comment]
SmartTopbar和SmartTopbar现已支持msg设置icon，使用最新版本2.6.0
